// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: bind_taxation.proto

package kkm_proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type BindedTaxation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaxationType *uint32                     `protobuf:"varint,1,req,name=taxation_type,json=taxationType" json:"taxation_type,omitempty"`
	Taxes        []*BindedTaxation_BindedTax `protobuf:"bytes,2,rep,name=taxes" json:"taxes,omitempty"`
}

func (x *BindedTaxation) Reset() {
	*x = BindedTaxation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bind_taxation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindedTaxation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindedTaxation) ProtoMessage() {}

func (x *BindedTaxation) ProtoReflect() protoreflect.Message {
	mi := &file_bind_taxation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindedTaxation.ProtoReflect.Descriptor instead.
func (*BindedTaxation) Descriptor() ([]byte, []int) {
	return file_bind_taxation_proto_rawDescGZIP(), []int{0}
}

func (x *BindedTaxation) GetTaxationType() uint32 {
	if x != nil && x.TaxationType != nil {
		return *x.TaxationType
	}
	return 0
}

func (x *BindedTaxation) GetTaxes() []*BindedTaxation_BindedTax {
	if x != nil {
		return x.Taxes
	}
	return nil
}

type BindedTaxation_BindedTax struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaxType *uint32 `protobuf:"varint,1,req,name=tax_type,json=taxType" json:"tax_type,omitempty"`
	Percent *uint32 `protobuf:"varint,2,req,name=percent" json:"percent,omitempty"`
}

func (x *BindedTaxation_BindedTax) Reset() {
	*x = BindedTaxation_BindedTax{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bind_taxation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BindedTaxation_BindedTax) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindedTaxation_BindedTax) ProtoMessage() {}

func (x *BindedTaxation_BindedTax) ProtoReflect() protoreflect.Message {
	mi := &file_bind_taxation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindedTaxation_BindedTax.ProtoReflect.Descriptor instead.
func (*BindedTaxation_BindedTax) Descriptor() ([]byte, []int) {
	return file_bind_taxation_proto_rawDescGZIP(), []int{0, 0}
}

func (x *BindedTaxation_BindedTax) GetTaxType() uint32 {
	if x != nil && x.TaxType != nil {
		return *x.TaxType
	}
	return 0
}

func (x *BindedTaxation_BindedTax) GetPercent() uint32 {
	if x != nil && x.Percent != nil {
		return *x.Percent
	}
	return 0
}

var File_bind_taxation_proto protoreflect.FileDescriptor

var file_bind_taxation_proto_rawDesc = []byte{
	0x0a, 0x13, 0x62, 0x69, 0x6e, 0x64, 0x5f, 0x74, 0x61, 0x78, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6b, 0x6b, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb2,
	0x01, 0x0a, 0x0e, 0x42, 0x69, 0x6e, 0x64, 0x65, 0x64, 0x54, 0x61, 0x78, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x61, 0x78, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x0c, 0x74, 0x61, 0x78, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x39, 0x0a, 0x05, 0x74, 0x61, 0x78, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6b, 0x6b, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x42, 0x69, 0x6e, 0x64, 0x65, 0x64, 0x54, 0x61, 0x78, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x42, 0x69, 0x6e, 0x64, 0x65, 0x64, 0x54, 0x61, 0x78, 0x52, 0x05, 0x74, 0x61, 0x78, 0x65,
	0x73, 0x1a, 0x40, 0x0a, 0x09, 0x42, 0x69, 0x6e, 0x64, 0x65, 0x64, 0x54, 0x61, 0x78, 0x12, 0x19,
	0x0a, 0x08, 0x74, 0x61, 0x78, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0d,
	0x52, 0x07, 0x74, 0x61, 0x78, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x72,
	0x63, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x07, 0x70, 0x65, 0x72, 0x63,
	0x65, 0x6e, 0x74, 0x42, 0x02, 0x48, 0x01,
}

var (
	file_bind_taxation_proto_rawDescOnce sync.Once
	file_bind_taxation_proto_rawDescData = file_bind_taxation_proto_rawDesc
)

func file_bind_taxation_proto_rawDescGZIP() []byte {
	file_bind_taxation_proto_rawDescOnce.Do(func() {
		file_bind_taxation_proto_rawDescData = protoimpl.X.CompressGZIP(file_bind_taxation_proto_rawDescData)
	})
	return file_bind_taxation_proto_rawDescData
}

var file_bind_taxation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bind_taxation_proto_goTypes = []interface{}{
	(*BindedTaxation)(nil),           // 0: kkm.proto.BindedTaxation
	(*BindedTaxation_BindedTax)(nil), // 1: kkm.proto.BindedTaxation.BindedTax
}
var file_bind_taxation_proto_depIdxs = []int32{
	1, // 0: kkm.proto.BindedTaxation.taxes:type_name -> kkm.proto.BindedTaxation.BindedTax
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bind_taxation_proto_init() }
func file_bind_taxation_proto_init() {
	if File_bind_taxation_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_bind_taxation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BindedTaxation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bind_taxation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BindedTaxation_BindedTax); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bind_taxation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bind_taxation_proto_goTypes,
		DependencyIndexes: file_bind_taxation_proto_depIdxs,
		MessageInfos:      file_bind_taxation_proto_msgTypes,
	}.Build()
	File_bind_taxation_proto = out.File
	file_bind_taxation_proto_rawDesc = nil
	file_bind_taxation_proto_goTypes = nil
	file_bind_taxation_proto_depIdxs = nil
}
