//* @file
// @brief Структуры сообщений для передачи и хранения информации по ккт.
//
// Содержит описания типов, хранящих информацию о кассе, торговой точке и организаци

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: reginfo.proto

package kkm_proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//*
// @brief Дополнительная информация по ккт - регистрационные данные.
//
type KkmRegInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	///Регистрационный номер (код) точки приема платежей
	PointOfPaymentNumber *string `protobuf:"bytes,1,opt,name=point_of_payment_number,json=pointOfPaymentNumber" json:"point_of_payment_number,omitempty"`
	///Номер платежного терминала
	TerminalNumber *string `protobuf:"bytes,2,opt,name=terminal_number,json=terminalNumber" json:"terminal_number,omitempty"`
	///ID, выданный ФНС
	FnsKkmId *string `protobuf:"bytes,3,opt,name=fns_kkm_id,json=fnsKkmId" json:"fns_kkm_id,omitempty"`
	/// Заводской номер ККМ
	SerialNumber *string `protobuf:"bytes,4,opt,name=serial_number,json=serialNumber" json:"serial_number,omitempty"`
}

func (x *KkmRegInfo) Reset() {
	*x = KkmRegInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reginfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KkmRegInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KkmRegInfo) ProtoMessage() {}

func (x *KkmRegInfo) ProtoReflect() protoreflect.Message {
	mi := &file_reginfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KkmRegInfo.ProtoReflect.Descriptor instead.
func (*KkmRegInfo) Descriptor() ([]byte, []int) {
	return file_reginfo_proto_rawDescGZIP(), []int{0}
}

func (x *KkmRegInfo) GetPointOfPaymentNumber() string {
	if x != nil && x.PointOfPaymentNumber != nil {
		return *x.PointOfPaymentNumber
	}
	return ""
}

func (x *KkmRegInfo) GetTerminalNumber() string {
	if x != nil && x.TerminalNumber != nil {
		return *x.TerminalNumber
	}
	return ""
}

func (x *KkmRegInfo) GetFnsKkmId() string {
	if x != nil && x.FnsKkmId != nil {
		return *x.FnsKkmId
	}
	return ""
}

func (x *KkmRegInfo) GetSerialNumber() string {
	if x != nil && x.SerialNumber != nil {
		return *x.SerialNumber
	}
	return ""
}

//*
// @brief Дополнительная информация по торговой точке - регистрационные данные.
//
type PosRegInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	/// Название торговой точки
	Title *string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	/// Адрес торговой точки
	Address *string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
}

func (x *PosRegInfo) Reset() {
	*x = PosRegInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reginfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PosRegInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PosRegInfo) ProtoMessage() {}

func (x *PosRegInfo) ProtoReflect() protoreflect.Message {
	mi := &file_reginfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PosRegInfo.ProtoReflect.Descriptor instead.
func (*PosRegInfo) Descriptor() ([]byte, []int) {
	return file_reginfo_proto_rawDescGZIP(), []int{1}
}

func (x *PosRegInfo) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *PosRegInfo) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

//*
// @brief Дополнительная информация по организации - регистрационные данные.
//
type OrgRegInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	/// Название организации или ФИО индивидуального предпринимателя
	Title *string `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	///  Юр. адрес
	Address *string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
	/// ИНН
	Inn *string `protobuf:"bytes,3,opt,name=inn" json:"inn,omitempty"`
	/// Вид налогообложения
	TaxationType *uint32 `protobuf:"varint,4,opt,name=taxation_type,json=taxationType" json:"taxation_type,omitempty"`
	/// Вид деятельности
	Okved *string `protobuf:"bytes,5,opt,name=okved" json:"okved,omitempty"`
}

func (x *OrgRegInfo) Reset() {
	*x = OrgRegInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reginfo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrgRegInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgRegInfo) ProtoMessage() {}

func (x *OrgRegInfo) ProtoReflect() protoreflect.Message {
	mi := &file_reginfo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgRegInfo.ProtoReflect.Descriptor instead.
func (*OrgRegInfo) Descriptor() ([]byte, []int) {
	return file_reginfo_proto_rawDescGZIP(), []int{2}
}

func (x *OrgRegInfo) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *OrgRegInfo) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *OrgRegInfo) GetInn() string {
	if x != nil && x.Inn != nil {
		return *x.Inn
	}
	return ""
}

func (x *OrgRegInfo) GetTaxationType() uint32 {
	if x != nil && x.TaxationType != nil {
		return *x.TaxationType
	}
	return 0
}

func (x *OrgRegInfo) GetOkved() string {
	if x != nil && x.Okved != nil {
		return *x.Okved
	}
	return ""
}

var File_reginfo_proto protoreflect.FileDescriptor

var file_reginfo_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x72, 0x65, 0x67, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x6b, 0x6b, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaf, 0x01, 0x0a, 0x0a, 0x4b,
	0x6b, 0x6d, 0x52, 0x65, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x35, 0x0a, 0x17, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x5f, 0x6f, 0x66, 0x5f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x4f, 0x66, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x27, 0x0a, 0x0f, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x6e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x74, 0x65, 0x72, 0x6d, 0x69,
	0x6e, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x0a, 0x66, 0x6e, 0x73,
	0x5f, 0x6b, 0x6b, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x6e, 0x73, 0x4b, 0x6b, 0x6d, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x3c, 0x0a, 0x0a,
	0x50, 0x6f, 0x73, 0x52, 0x65, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x89, 0x01, 0x0a, 0x0a, 0x4f,
	0x72, 0x67, 0x52, 0x65, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6e, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x6e, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x74,
	0x61, 0x78, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0c, 0x74, 0x61, 0x78, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x6f, 0x6b, 0x76, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6f, 0x6b, 0x76, 0x65, 0x64, 0x42, 0x02, 0x48, 0x01,
}

var (
	file_reginfo_proto_rawDescOnce sync.Once
	file_reginfo_proto_rawDescData = file_reginfo_proto_rawDesc
)

func file_reginfo_proto_rawDescGZIP() []byte {
	file_reginfo_proto_rawDescOnce.Do(func() {
		file_reginfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_reginfo_proto_rawDescData)
	})
	return file_reginfo_proto_rawDescData
}

var file_reginfo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_reginfo_proto_goTypes = []interface{}{
	(*KkmRegInfo)(nil), // 0: kkm.proto.KkmRegInfo
	(*PosRegInfo)(nil), // 1: kkm.proto.PosRegInfo
	(*OrgRegInfo)(nil), // 2: kkm.proto.OrgRegInfo
}
var file_reginfo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_reginfo_proto_init() }
func file_reginfo_proto_init() {
	if File_reginfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_reginfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KkmRegInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reginfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PosRegInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reginfo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrgRegInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reginfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reginfo_proto_goTypes,
		DependencyIndexes: file_reginfo_proto_depIdxs,
		MessageInfos:      file_reginfo_proto_msgTypes,
	}.Build()
	File_reginfo_proto = out.File
	file_reginfo_proto_rawDesc = nil
	file_reginfo_proto_goTypes = nil
	file_reginfo_proto_depIdxs = nil
}
