//*
// @file
// @brief Служебные типы данных.
//
// Содержит описания типов данных, используемых в служебном обмене.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: service.proto

package kkm_proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ServiceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommQuality         *ServiceRequest_CommQuality   `protobuf:"bytes,1,opt,name=comm_quality,json=commQuality" json:"comm_quality,omitempty"`
	SecurityStats       *ServiceRequest_SecurityStats `protobuf:"bytes,3,opt,name=security_stats,json=securityStats" json:"security_stats,omitempty"`
	OfflinePeriod       *ServiceRequest_OfflinePeriod `protobuf:"bytes,4,opt,name=offline_period,json=offlinePeriod" json:"offline_period,omitempty"`
	NomenclatureVersion *uint32                       `protobuf:"varint,5,opt,name=nomenclature_version,json=nomenclatureVersion" json:"nomenclature_version,omitempty"`
	TicketAdInfos       []*TicketAdInfo               `protobuf:"bytes,6,rep,name=ticket_ad_infos,json=ticketAdInfos" json:"ticket_ad_infos,omitempty"`
	GetRegInfo          *bool                         `protobuf:"varint,7,opt,name=get_reg_info,json=getRegInfo" json:"get_reg_info,omitempty"`
	GetBindedTaxation   *bool                         `protobuf:"varint,8,opt,name=get_binded_taxation,json=getBindedTaxation" json:"get_binded_taxation,omitempty"`
	Marker              *uint64                       `protobuf:"varint,9,opt,name=marker" json:"marker,omitempty"`
	// /**
	//   * @brief Информация о программном (и не только) обеспечении.
	//   */
	//   message SoftwareInformation {
	//
	//   /**
	//     * @brief Информация о программном модуле (vpm библиотека, партнёрское ПО и т.д.).
	//     */
	//     message ModuleInformation {
	//
	//     /**
	//       * @brief Информация об устройстве (для мобильных платформ или ФР).
	//       */
	//       message DeviceInformation {
	//         optional string manufacturer = 1;
	//         optional string model = 2;
	//         optional string firmware_version = 3;
	//       }
	//
	//       required string name = 1;
	//       required string version = 2;
	//       optional string build_info = 3;
	//       // optional DeviceInformation device_info = 4;
	//       repeated KeyValuePair extended_info = 5;
	//       optional string build_arch = 6;
	//     }
	//
	//     repeated ModuleInformation module_infos = 1;
	//     optional string hardware_arch = 2;
	//     optional string os_family = 3;
	//     optional string os_version = 4;
	//     optional string os_extended_info = 5;
	//     optional string runtime_version = 6;
	//     optional uint32 partner_id = 7;
	//   }
	// optional SoftwareInformation software_information = 11;
	RegInfo_ *ServiceRequest_RegInfo `protobuf:"bytes,12,opt,name=reg_info,json=regInfo" json:"reg_info,omitempty"`
	// repeated KeyValuePair auxiliary = 13;
	Auxiliary []*KeyValuePair `protobuf:"bytes,60,rep,name=auxiliary" json:"auxiliary,omitempty"`
}

func (x *ServiceRequest) Reset() {
	*x = ServiceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRequest) ProtoMessage() {}

func (x *ServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRequest.ProtoReflect.Descriptor instead.
func (*ServiceRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceRequest) GetCommQuality() *ServiceRequest_CommQuality {
	if x != nil {
		return x.CommQuality
	}
	return nil
}

func (x *ServiceRequest) GetSecurityStats() *ServiceRequest_SecurityStats {
	if x != nil {
		return x.SecurityStats
	}
	return nil
}

func (x *ServiceRequest) GetOfflinePeriod() *ServiceRequest_OfflinePeriod {
	if x != nil {
		return x.OfflinePeriod
	}
	return nil
}

func (x *ServiceRequest) GetNomenclatureVersion() uint32 {
	if x != nil && x.NomenclatureVersion != nil {
		return *x.NomenclatureVersion
	}
	return 0
}

func (x *ServiceRequest) GetTicketAdInfos() []*TicketAdInfo {
	if x != nil {
		return x.TicketAdInfos
	}
	return nil
}

func (x *ServiceRequest) GetGetRegInfo() bool {
	if x != nil && x.GetRegInfo != nil {
		return *x.GetRegInfo
	}
	return false
}

func (x *ServiceRequest) GetGetBindedTaxation() bool {
	if x != nil && x.GetBindedTaxation != nil {
		return *x.GetBindedTaxation
	}
	return false
}

func (x *ServiceRequest) GetMarker() uint64 {
	if x != nil && x.Marker != nil {
		return *x.Marker
	}
	return 0
}

func (x *ServiceRequest) GetRegInfo_() *ServiceRequest_RegInfo {
	if x != nil {
		return x.RegInfo_
	}
	return nil
}

func (x *ServiceRequest) GetAuxiliary() []*KeyValuePair {
	if x != nil {
		return x.Auxiliary
	}
	return nil
}

type ServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TicketAds      []*TicketAd              `protobuf:"bytes,1,rep,name=ticket_ads,json=ticketAds" json:"ticket_ads,omitempty"`
	RegInfo        *ServiceResponse_RegInfo `protobuf:"bytes,2,opt,name=reg_info,json=regInfo" json:"reg_info,omitempty"`
	BindedTaxation *BindedTaxation          `protobuf:"bytes,3,opt,name=binded_taxation,json=bindedTaxation" json:"binded_taxation,omitempty"`
	Auxiliary      []*KeyValuePair          `protobuf:"bytes,30,rep,name=auxiliary" json:"auxiliary,omitempty"`
}

func (x *ServiceResponse) Reset() {
	*x = ServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceResponse) ProtoMessage() {}

func (x *ServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceResponse.ProtoReflect.Descriptor instead.
func (*ServiceResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceResponse) GetTicketAds() []*TicketAd {
	if x != nil {
		return x.TicketAds
	}
	return nil
}

func (x *ServiceResponse) GetRegInfo() *ServiceResponse_RegInfo {
	if x != nil {
		return x.RegInfo
	}
	return nil
}

func (x *ServiceResponse) GetBindedTaxation() *BindedTaxation {
	if x != nil {
		return x.BindedTaxation
	}
	return nil
}

func (x *ServiceResponse) GetAuxiliary() []*KeyValuePair {
	if x != nil {
		return x.Auxiliary
	}
	return nil
}

//*
// @brief Информация о качестве связи.
//
type ServiceRequest_CommQuality struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AvgConnectTime *uint32 `protobuf:"varint,1,req,name=avg_connect_time,json=avgConnectTime" json:"avg_connect_time,omitempty"`
	AvgPing        *uint32 `protobuf:"varint,2,opt,name=avg_ping,json=avgPing" json:"avg_ping,omitempty"`
	LossRatio      *uint32 `protobuf:"varint,3,opt,name=loss_ratio,json=lossRatio" json:"loss_ratio,omitempty"`
}

func (x *ServiceRequest_CommQuality) Reset() {
	*x = ServiceRequest_CommQuality{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceRequest_CommQuality) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRequest_CommQuality) ProtoMessage() {}

func (x *ServiceRequest_CommQuality) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRequest_CommQuality.ProtoReflect.Descriptor instead.
func (*ServiceRequest_CommQuality) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ServiceRequest_CommQuality) GetAvgConnectTime() uint32 {
	if x != nil && x.AvgConnectTime != nil {
		return *x.AvgConnectTime
	}
	return 0
}

func (x *ServiceRequest_CommQuality) GetAvgPing() uint32 {
	if x != nil && x.AvgPing != nil {
		return *x.AvgPing
	}
	return 0
}

func (x *ServiceRequest_CommQuality) GetLossRatio() uint32 {
	if x != nil && x.LossRatio != nil {
		return *x.LossRatio
	}
	return 0
}

//*
// @brief Безопасность и статистика.
//
type ServiceRequest_SecurityStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GeoPosition *ServiceRequest_SecurityStats_GeoPosition `protobuf:"bytes,1,opt,name=geo_position,json=geoPosition" json:"geo_position,omitempty"`
	//*
	// @deprecated
	OsVersion *string `protobuf:"bytes,2,opt,name=os_version,json=osVersion" json:"os_version,omitempty"`
}

func (x *ServiceRequest_SecurityStats) Reset() {
	*x = ServiceRequest_SecurityStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceRequest_SecurityStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRequest_SecurityStats) ProtoMessage() {}

func (x *ServiceRequest_SecurityStats) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRequest_SecurityStats.ProtoReflect.Descriptor instead.
func (*ServiceRequest_SecurityStats) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ServiceRequest_SecurityStats) GetGeoPosition() *ServiceRequest_SecurityStats_GeoPosition {
	if x != nil {
		return x.GeoPosition
	}
	return nil
}

func (x *ServiceRequest_SecurityStats) GetOsVersion() string {
	if x != nil && x.OsVersion != nil {
		return *x.OsVersion
	}
	return ""
}

//*
// @brief Время нахождения в аварийном режиме.
//
// Период времени, в течение которого ККМ находилась в аварийном режиме.
type ServiceRequest_OfflinePeriod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BeginTime *DateTime `protobuf:"bytes,1,req,name=begin_time,json=beginTime" json:"begin_time,omitempty"`
	EndTime   *DateTime `protobuf:"bytes,2,req,name=end_time,json=endTime" json:"end_time,omitempty"`
}

func (x *ServiceRequest_OfflinePeriod) Reset() {
	*x = ServiceRequest_OfflinePeriod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceRequest_OfflinePeriod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRequest_OfflinePeriod) ProtoMessage() {}

func (x *ServiceRequest_OfflinePeriod) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRequest_OfflinePeriod.ProtoReflect.Descriptor instead.
func (*ServiceRequest_OfflinePeriod) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0, 2}
}

func (x *ServiceRequest_OfflinePeriod) GetBeginTime() *DateTime {
	if x != nil {
		return x.BeginTime
	}
	return nil
}

func (x *ServiceRequest_OfflinePeriod) GetEndTime() *DateTime {
	if x != nil {
		return x.EndTime
	}
	return nil
}

type ServiceRequest_RegInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kkm *KkmRegInfo `protobuf:"bytes,1,opt,name=kkm" json:"kkm,omitempty"`
	Org *OrgRegInfo `protobuf:"bytes,2,opt,name=org" json:"org,omitempty"`
}

func (x *ServiceRequest_RegInfo) Reset() {
	*x = ServiceRequest_RegInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceRequest_RegInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRequest_RegInfo) ProtoMessage() {}

func (x *ServiceRequest_RegInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRequest_RegInfo.ProtoReflect.Descriptor instead.
func (*ServiceRequest_RegInfo) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0, 3}
}

func (x *ServiceRequest_RegInfo) GetKkm() *KkmRegInfo {
	if x != nil {
		return x.Kkm
	}
	return nil
}

func (x *ServiceRequest_RegInfo) GetOrg() *OrgRegInfo {
	if x != nil {
		return x.Org
	}
	return nil
}

type ServiceRequest_SecurityStats_GeoPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  *int32 `protobuf:"varint,1,req,name=latitude" json:"latitude,omitempty"`
	Longitude *int32 `protobuf:"varint,2,req,name=longitude" json:"longitude,omitempty"`
}

func (x *ServiceRequest_SecurityStats_GeoPosition) Reset() {
	*x = ServiceRequest_SecurityStats_GeoPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceRequest_SecurityStats_GeoPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRequest_SecurityStats_GeoPosition) ProtoMessage() {}

func (x *ServiceRequest_SecurityStats_GeoPosition) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRequest_SecurityStats_GeoPosition.ProtoReflect.Descriptor instead.
func (*ServiceRequest_SecurityStats_GeoPosition) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *ServiceRequest_SecurityStats_GeoPosition) GetLatitude() int32 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *ServiceRequest_SecurityStats_GeoPosition) GetLongitude() int32 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

type ServiceResponse_RegInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kkm *KkmRegInfo `protobuf:"bytes,1,opt,name=kkm" json:"kkm,omitempty"`
	Pos *PosRegInfo `protobuf:"bytes,2,opt,name=pos" json:"pos,omitempty"`
	Org *OrgRegInfo `protobuf:"bytes,3,opt,name=org" json:"org,omitempty"`
}

func (x *ServiceResponse_RegInfo) Reset() {
	*x = ServiceResponse_RegInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceResponse_RegInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceResponse_RegInfo) ProtoMessage() {}

func (x *ServiceResponse_RegInfo) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceResponse_RegInfo.ProtoReflect.Descriptor instead.
func (*ServiceResponse_RegInfo) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ServiceResponse_RegInfo) GetKkm() *KkmRegInfo {
	if x != nil {
		return x.Kkm
	}
	return nil
}

func (x *ServiceResponse_RegInfo) GetPos() *PosRegInfo {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *ServiceResponse_RegInfo) GetOrg() *OrgRegInfo {
	if x != nil {
		return x.Org
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

var file_service_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x6b, 0x6b, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x72, 0x65, 0x67, 0x69, 0x6e, 0x66,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x62, 0x69, 0x6e, 0x64, 0x5f, 0x74, 0x61,
	0x78, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe4, 0x08, 0x0a,
	0x0e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x48, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x5f, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6b, 0x6b, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x0b, 0x63, 0x6f,
	0x6d, 0x6d, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x4e, 0x0a, 0x0e, 0x73, 0x65, 0x63,
	0x75, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x6b, 0x6b, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x65, 0x63,
	0x75, 0x72, 0x69, 0x74, 0x79, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x0d, 0x73, 0x65, 0x63, 0x75,
	0x72, 0x69, 0x74, 0x79, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x4e, 0x0a, 0x0e, 0x6f, 0x66, 0x66,
	0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x6b, 0x6b, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x66, 0x66,
	0x6c, 0x69, 0x6e, 0x65, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x52, 0x0d, 0x6f, 0x66, 0x66, 0x6c,
	0x69, 0x6e, 0x65, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x31, 0x0a, 0x14, 0x6e, 0x6f, 0x6d,
	0x65, 0x6e, 0x63, 0x6c, 0x61, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x13, 0x6e, 0x6f, 0x6d, 0x65, 0x6e, 0x63, 0x6c,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x3f, 0x0a, 0x0f,
	0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x61, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18,
	0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6b, 0x6b, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x41, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d,
	0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x41, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x20, 0x0a,
	0x0c, 0x67, 0x65, 0x74, 0x5f, 0x72, 0x65, 0x67, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x67, 0x65, 0x74, 0x52, 0x65, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x2e, 0x0a, 0x13, 0x67, 0x65, 0x74, 0x5f, 0x62, 0x69, 0x6e, 0x64, 0x65, 0x64, 0x5f, 0x74, 0x61,
	0x78, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x67, 0x65,
	0x74, 0x42, 0x69, 0x6e, 0x64, 0x65, 0x64, 0x54, 0x61, 0x78, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x3c, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x6b, 0x6b, 0x6d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x72, 0x65,
	0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x35, 0x0a, 0x09, 0x61, 0x75, 0x78, 0x69, 0x6c, 0x69, 0x61,
	0x72, 0x79, 0x18, 0x3c, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6b, 0x6b, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61, 0x69,
	0x72, 0x52, 0x09, 0x61, 0x75, 0x78, 0x69, 0x6c, 0x69, 0x61, 0x72, 0x79, 0x1a, 0x71, 0x0a, 0x0b,
	0x43, 0x6f, 0x6d, 0x6d, 0x51, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x28, 0x0a, 0x10, 0x61,
	0x76, 0x67, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x0e, 0x61, 0x76, 0x67, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x76, 0x67, 0x5f, 0x70, 0x69, 0x6e,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x61, 0x76, 0x67, 0x50, 0x69, 0x6e, 0x67,
	0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x6f, 0x73, 0x73, 0x5f, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x6c, 0x6f, 0x73, 0x73, 0x52, 0x61, 0x74, 0x69, 0x6f, 0x1a,
	0xcf, 0x01, 0x0a, 0x0d, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x12, 0x56, 0x0a, 0x0c, 0x67, 0x65, 0x6f, 0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x6b, 0x6b, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x2e, 0x47, 0x65, 0x6f, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x67, 0x65,
	0x6f, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x6f, 0x73, 0x5f,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6f,
	0x73, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x47, 0x0a, 0x0b, 0x47, 0x65, 0x6f, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74,
	0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x05, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64,
	0x65, 0x1a, 0x73, 0x0a, 0x0d, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x50, 0x65, 0x72, 0x69,
	0x6f, 0x64, 0x12, 0x32, 0x0a, 0x0a, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6b, 0x6b, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x09, 0x62, 0x65, 0x67,
	0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6b, 0x6b, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x52, 0x07, 0x65,
	0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x1a, 0x5b, 0x0a, 0x07, 0x52, 0x65, 0x67, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x27, 0x0a, 0x03, 0x6b, 0x6b, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x6b, 0x6b, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4b, 0x6b, 0x6d, 0x52, 0x65,
	0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x6b, 0x6b, 0x6d, 0x12, 0x27, 0x0a, 0x03, 0x6f, 0x72,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6b, 0x6b, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03,
	0x6f, 0x72, 0x67, 0x22, 0x86, 0x03, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x0a, 0x74, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x5f, 0x61, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6b, 0x6b,
	0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x41, 0x64,
	0x52, 0x09, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x41, 0x64, 0x73, 0x12, 0x3d, 0x0a, 0x08, 0x72,
	0x65, 0x67, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e,
	0x6b, 0x6b, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x67, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x07, 0x72, 0x65, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x42, 0x0a, 0x0f, 0x62, 0x69,
	0x6e, 0x64, 0x65, 0x64, 0x5f, 0x74, 0x61, 0x78, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6b, 0x6b, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x42, 0x69, 0x6e, 0x64, 0x65, 0x64, 0x54, 0x61, 0x78, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0e,
	0x62, 0x69, 0x6e, 0x64, 0x65, 0x64, 0x54, 0x61, 0x78, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x35,
	0x0a, 0x09, 0x61, 0x75, 0x78, 0x69, 0x6c, 0x69, 0x61, 0x72, 0x79, 0x18, 0x1e, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x6b, 0x6b, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4b, 0x65,
	0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x50, 0x61, 0x69, 0x72, 0x52, 0x09, 0x61, 0x75, 0x78, 0x69,
	0x6c, 0x69, 0x61, 0x72, 0x79, 0x1a, 0x84, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x67, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x27, 0x0a, 0x03, 0x6b, 0x6b, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x6b, 0x6b, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4b, 0x6b, 0x6d, 0x52, 0x65,
	0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x6b, 0x6b, 0x6d, 0x12, 0x27, 0x0a, 0x03, 0x70, 0x6f,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6b, 0x6b, 0x6d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6f, 0x73, 0x52, 0x65, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03,
	0x70, 0x6f, 0x73, 0x12, 0x27, 0x0a, 0x03, 0x6f, 0x72, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x6b, 0x6b, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4f, 0x72, 0x67,
	0x52, 0x65, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x03, 0x6f, 0x72, 0x67, 0x42, 0x02, 0x48, 0x01,
}

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData = file_service_proto_rawDesc
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_proto_rawDescData)
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_service_proto_goTypes = []interface{}{
	(*ServiceRequest)(nil),                           // 0: kkm.proto.ServiceRequest
	(*ServiceResponse)(nil),                          // 1: kkm.proto.ServiceResponse
	(*ServiceRequest_CommQuality)(nil),               // 2: kkm.proto.ServiceRequest.CommQuality
	(*ServiceRequest_SecurityStats)(nil),             // 3: kkm.proto.ServiceRequest.SecurityStats
	(*ServiceRequest_OfflinePeriod)(nil),             // 4: kkm.proto.ServiceRequest.OfflinePeriod
	(*ServiceRequest_RegInfo)(nil),                   // 5: kkm.proto.ServiceRequest.RegInfo
	(*ServiceRequest_SecurityStats_GeoPosition)(nil), // 6: kkm.proto.ServiceRequest.SecurityStats.GeoPosition
	(*ServiceResponse_RegInfo)(nil),                  // 7: kkm.proto.ServiceResponse.RegInfo
	(*TicketAdInfo)(nil),                             // 8: kkm.proto.TicketAdInfo
	(*KeyValuePair)(nil),                             // 9: kkm.proto.KeyValuePair
	(*TicketAd)(nil),                                 // 10: kkm.proto.TicketAd
	(*BindedTaxation)(nil),                           // 11: kkm.proto.BindedTaxation
	(*DateTime)(nil),                                 // 12: kkm.proto.DateTime
	(*KkmRegInfo)(nil),                               // 13: kkm.proto.KkmRegInfo
	(*OrgRegInfo)(nil),                               // 14: kkm.proto.OrgRegInfo
	(*PosRegInfo)(nil),                               // 15: kkm.proto.PosRegInfo
}
var file_service_proto_depIdxs = []int32{
	2,  // 0: kkm.proto.ServiceRequest.comm_quality:type_name -> kkm.proto.ServiceRequest.CommQuality
	3,  // 1: kkm.proto.ServiceRequest.security_stats:type_name -> kkm.proto.ServiceRequest.SecurityStats
	4,  // 2: kkm.proto.ServiceRequest.offline_period:type_name -> kkm.proto.ServiceRequest.OfflinePeriod
	8,  // 3: kkm.proto.ServiceRequest.ticket_ad_infos:type_name -> kkm.proto.TicketAdInfo
	5,  // 4: kkm.proto.ServiceRequest.reg_info:type_name -> kkm.proto.ServiceRequest.RegInfo
	9,  // 5: kkm.proto.ServiceRequest.auxiliary:type_name -> kkm.proto.KeyValuePair
	10, // 6: kkm.proto.ServiceResponse.ticket_ads:type_name -> kkm.proto.TicketAd
	7,  // 7: kkm.proto.ServiceResponse.reg_info:type_name -> kkm.proto.ServiceResponse.RegInfo
	11, // 8: kkm.proto.ServiceResponse.binded_taxation:type_name -> kkm.proto.BindedTaxation
	9,  // 9: kkm.proto.ServiceResponse.auxiliary:type_name -> kkm.proto.KeyValuePair
	6,  // 10: kkm.proto.ServiceRequest.SecurityStats.geo_position:type_name -> kkm.proto.ServiceRequest.SecurityStats.GeoPosition
	12, // 11: kkm.proto.ServiceRequest.OfflinePeriod.begin_time:type_name -> kkm.proto.DateTime
	12, // 12: kkm.proto.ServiceRequest.OfflinePeriod.end_time:type_name -> kkm.proto.DateTime
	13, // 13: kkm.proto.ServiceRequest.RegInfo.kkm:type_name -> kkm.proto.KkmRegInfo
	14, // 14: kkm.proto.ServiceRequest.RegInfo.org:type_name -> kkm.proto.OrgRegInfo
	13, // 15: kkm.proto.ServiceResponse.RegInfo.kkm:type_name -> kkm.proto.KkmRegInfo
	15, // 16: kkm.proto.ServiceResponse.RegInfo.pos:type_name -> kkm.proto.PosRegInfo
	14, // 17: kkm.proto.ServiceResponse.RegInfo.org:type_name -> kkm.proto.OrgRegInfo
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_common_proto_init()
	file_reginfo_proto_init()
	file_bind_taxation_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceRequest_CommQuality); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceRequest_SecurityStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceRequest_OfflinePeriod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceRequest_RegInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceRequest_SecurityStats_GeoPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceResponse_RegInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_rawDesc = nil
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
