// Package models contains the types for schema 'dbo'.
package models

// Code generated by xo. DO NOT EDIT.

// Address represents a row from 'dbo.Address'.
type Address struct {
	Id int `gorm:"PRIMARY_KEY;column:idAddress"` // idAddress
	//IdTypeaddress int         `gorm:"column:idTypeAddress"`         // idTypeAddress
	IdTown int    `gorm:"column:idTown"` // idTown
	Street string `gorm:"column:Street"` // Street
	House  string `gorm:"column:House"`  // House
	Flat   string `gorm:"column:Flat"`   // Flat
	//TypeAddress   Typeaddress `gorm:"foreignkey:IdTypeaddress; auto_preload:true"`
	Town Town `gorm:"foreignkey:IdTown; auto_preload:true"`
}

// TableName sets the insert table name for this struct type
func (self Address) TableName() string {
	return "Address"
}
