// Package models contains the types for schema 'dbo'.
package models

/*
// Code generated by xo. DO NOT EDIT.

import (
	"time"
)

// Operation represents a row from 'dbo.Operations'.
type Operation struct {
	Id            int       `gorm:"PRIMARY_KEY;column:idOperations"`                // idOperations
	IdDocuments   int       `gorm:"column:idDocuments"`                             // idDocuments
	Value         Decimal   `gorm:"column:Value"`                                   // Сумма
	Dateoperation time.Time `gorm:"column:DateOperation;default:CURRENT_TIMESTAMP"` // DateOperation
}

// TableName sets the insert table name for this struct type
func (self Operation) TableName() string {
	return "Operations"
}
*/
