package fiscal_operations

const (
	OPERATION_SALE            = 1
	OPERATION_FUND            = 2
	OPERATION_WITHDRAW        = 3
	OPERATION_PURCHASE        = 4
	OPERATION_REFUND          = 5
	OPERATION_OPEN_SHIFT      = 6
	OPERATION_CLOSE_SHIFT     = 7
	OPERATION_REPORT_X        = 8
	OPERATION_PURCHASE_REFUND = 9
)
